# Generated by Django 5.0.6 on 2026-04-02 16:52

from django.db import migrations, models
import json

def load_prompts(apps, schema_editor):
    AIPrompt = apps.get_model('chat', 'AIPrompt')
    
    from prompts.v2 import (
        EMOTION_CLASSIFY_PROMPTS,
        SYSTEM_PROMPTS,
        EMOTION_PROMPTS,
        STAGE_PROMPTS,
        ANTI_REPETITION_PROMPT,
        QUESTION_HANDLING_PROMPT,
        JOURNAL_INSIGHT_PROMPT,
        TIMELINE_INSIGHT_PROMPT,
        CBT_FOLLOW_UPS,
        CRISIS_SYSTEM_PROMPT,
        CRISIS_RESPONSE_FALLBACK,
        SMART_ACTIONS
    )

    AIPrompt.objects.create(name="emotion_classify_prompt", content=EMOTION_CLASSIFY_PROMPTS)
    AIPrompt.objects.create(name="base_system_prompt", content=SYSTEM_PROMPTS)
    AIPrompt.objects.create(name="anti_repetition_prompt", content=ANTI_REPETITION_PROMPT)
    AIPrompt.objects.create(name="question_handling_prompt", content=QUESTION_HANDLING_PROMPT)
    AIPrompt.objects.create(name="journal_insight_prompt", content=JOURNAL_INSIGHT_PROMPT)
    AIPrompt.objects.create(name="timeline_insight_prompt", content=TIMELINE_INSIGHT_PROMPT)

    for emotion, text in EMOTION_PROMPTS.items():
        AIPrompt.objects.create(name="emotion_prompt", emotion=emotion, content=text)
        
    for stage, text in STAGE_PROMPTS.items():
        AIPrompt.objects.create(name="stage_prompt", emotion=stage, content=text)

    for emotion, text in CBT_FOLLOW_UPS.items():
        AIPrompt.objects.create(name="cbt_prompt", emotion=emotion, content=text)

    AIPrompt.objects.create(name="crisis_system_prompt", emotion=None, content=CRISIS_SYSTEM_PROMPT)
    AIPrompt.objects.create(name="crisis_fallback", emotion=None, content=CRISIS_RESPONSE_FALLBACK["message"])

    for emotion, action_dict in SMART_ACTIONS.items():
        AIPrompt.objects.create(name="smart_action", emotion=emotion, content=json.dumps(action_dict))



class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('emotion', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('name', 'emotion')},
            },
        ),
        migrations.RunPython(load_prompts),
    ]
