# Generated by Django 5.0.6 on 2026-04-05

import json
from django.db import migrations


def add_neutral_prompt_support(apps, schema_editor):
    AIPrompt = apps.get_model("chat", "AIPrompt")

    from prompts.v2 import EMOTION_CLASSIFY_PROMPTS, EMOTION_PROMPTS, SMART_ACTIONS

    AIPrompt.objects.update_or_create(
        name="emotion_classify_prompt",
        emotion=None,
        defaults={"content": EMOTION_CLASSIFY_PROMPTS},
    )

    neutral_emotion_prompt = EMOTION_PROMPTS.get("neutral")
    if neutral_emotion_prompt:
        AIPrompt.objects.update_or_create(
            name="emotion_prompt",
            emotion="neutral",
            defaults={"content": neutral_emotion_prompt},
        )

    neutral_smart_action = SMART_ACTIONS.get("neutral")
    if neutral_smart_action:
        AIPrompt.objects.update_or_create(
            name="smart_action",
            emotion="neutral",
            defaults={"content": json.dumps(neutral_smart_action)},
        )


def remove_neutral_prompt_support(apps, schema_editor):
    AIPrompt = apps.get_model("chat", "AIPrompt")

    AIPrompt.objects.filter(name="emotion_prompt", emotion="neutral").delete()
    AIPrompt.objects.filter(name="smart_action", emotion="neutral").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_conversation_journal_context"),
    ]

    operations = [
        migrations.RunPython(add_neutral_prompt_support, remove_neutral_prompt_support),
    ]
