# Generated by Django 5.0.6 on 2026-04-02 03:27

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knowledge', '0001_enable_pgvector'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('cbt_technique', 'CBT Technique'), ('breathing_grounding', 'Breathing / Grounding'), ('reflection_question', 'Reflection Question'), ('psychoeducation', 'Psychoeducation'), ('crisis_resource', 'Crisis Resource')], max_length=50)),
                ('emotion_tag', models.CharField(blank=True, max_length=20)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=384)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
