# Generated by Django 5.0.6 on 2026-04-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgechunk',
            name='category',
            field=models.CharField(choices=[('cbt_technique', 'CBT Technique'), ('breathing_grounding', 'Breathing / Grounding'), ('reflection_question', 'Reflection Question'), ('psychoeducation', 'Psychoeducation'), ('insight', 'Insight'), ('reframe', 'Reframe'), ('validation', 'Validation'), ('perspective', 'Perspective'), ('question', 'Question'), ('technique', 'Technique'), ('crisis_resource', 'Crisis Resource')], max_length=50),
        ),
    ]
